"""modified models

Revision ID: 39dd3586ea89
Revises: c62ceb064523
Create Date: 2023-07-25 20:28:37.327945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dd3586ea89'
down_revision = 'c62ceb064523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.alter_column('departure',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.alter_column('departure',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
