"""modified models

Revision ID: 7b977206c801
Revises: c0f4a1bbcf7c
Create Date: 2023-07-25 20:21:27.964975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b977206c801'
down_revision = 'c0f4a1bbcf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
