"""made some changes

Revision ID: 7ddc40ff0f2d
Revises: 39dd3586ea89
Create Date: 2023-07-26 22:29:10.691482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddc40ff0f2d'
down_revision = '39dd3586ea89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('From', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('To', sa.String(), nullable=True))
        batch_op.drop_column('route')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('To')
        batch_op.drop_column('From')

    # ### end Alembic commands ###
